Numpy Fundamentals-array creation ,indexing, slicing

In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("Iris.csv")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [8]:
sepal_length = df['SepalLengthCm'].to_numpy()
sepal_length

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [10]:
type(sepal_length)

numpy.ndarray

In [12]:
sepal_length[0]

5.1

In [14]:
sepal_length[:5]

array([5.1, 4.9, 4.7, 4.6, 5. ])

In [15]:
sepal_length[-5:]

array([6.7, 6.3, 6.5, 6.2, 5.9])

Mathematical, axis-wise & statistical operations

In [16]:
np.mean(sepal_length)

5.843333333333334

In [17]:
np.median(sepal_length)

5.8

In [18]:
np.max(sepal_length)

7.9

In [19]:
np.min(sepal_length)

4.3

In [20]:
np.std(sepal_length)

0.8253012917851409

Reshaping & broadcasting

In [21]:
sepal_length +1

array([6.1, 5.9, 5.7, 5.6, 6. , 6.4, 5.6, 6. , 5.4, 5.9, 6.4, 5.8, 5.8,
       5.3, 6.8, 6.7, 6.4, 6.1, 6.7, 6.1, 6.4, 6.1, 5.6, 6.1, 5.8, 6. ,
       6. , 6.2, 6.2, 5.7, 5.8, 6.4, 6.2, 6.5, 5.9, 6. , 6.5, 5.9, 5.4,
       6.1, 6. , 5.5, 5.4, 6. , 6.1, 5.8, 6.1, 5.6, 6.3, 6. , 8. , 7.4,
       7.9, 6.5, 7.5, 6.7, 7.3, 5.9, 7.6, 6.2, 6. , 6.9, 7. , 7.1, 6.6,
       7.7, 6.6, 6.8, 7.2, 6.6, 6.9, 7.1, 7.3, 7.1, 7.4, 7.6, 7.8, 7.7,
       7. , 6.7, 6.5, 6.5, 6.8, 7. , 6.4, 7. , 7.7, 7.3, 6.6, 6.5, 6.5,
       7.1, 6.8, 6. , 6.6, 6.7, 6.7, 7.2, 6.1, 6.7, 7.3, 6.8, 8.1, 7.3,
       7.5, 8.6, 5.9, 8.3, 7.7, 8.2, 7.5, 7.4, 7.8, 6.7, 6.8, 7.4, 7.5,
       8.7, 8.7, 7. , 7.9, 6.6, 8.7, 7.3, 7.7, 8.2, 7.2, 7.1, 7.4, 8.2,
       8.4, 8.9, 7.4, 7.3, 7.1, 8.7, 7.3, 7.4, 7. , 7.9, 7.7, 7.9, 6.8,
       7.8, 7.7, 7.7, 7.3, 7.5, 7.2, 6.9])

In [22]:
sepal_length *2

array([10.2,  9.8,  9.4,  9.2, 10. , 10.8,  9.2, 10. ,  8.8,  9.8, 10.8,
        9.6,  9.6,  8.6, 11.6, 11.4, 10.8, 10.2, 11.4, 10.2, 10.8, 10.2,
        9.2, 10.2,  9.6, 10. , 10. , 10.4, 10.4,  9.4,  9.6, 10.8, 10.4,
       11. ,  9.8, 10. , 11. ,  9.8,  8.8, 10.2, 10. ,  9. ,  8.8, 10. ,
       10.2,  9.6, 10.2,  9.2, 10.6, 10. , 14. , 12.8, 13.8, 11. , 13. ,
       11.4, 12.6,  9.8, 13.2, 10.4, 10. , 11.8, 12. , 12.2, 11.2, 13.4,
       11.2, 11.6, 12.4, 11.2, 11.8, 12.2, 12.6, 12.2, 12.8, 13.2, 13.6,
       13.4, 12. , 11.4, 11. , 11. , 11.6, 12. , 10.8, 12. , 13.4, 12.6,
       11.2, 11. , 11. , 12.2, 11.6, 10. , 11.2, 11.4, 11.4, 12.4, 10.2,
       11.4, 12.6, 11.6, 14.2, 12.6, 13. , 15.2,  9.8, 14.6, 13.4, 14.4,
       13. , 12.8, 13.6, 11.4, 11.6, 12.8, 13. , 15.4, 15.4, 12. , 13.8,
       11.2, 15.4, 12.6, 13.4, 14.4, 12.4, 12.2, 12.8, 14.4, 14.8, 15.8,
       12.8, 12.6, 12.2, 15.4, 12.6, 12.8, 12. , 13.8, 13.4, 13.8, 11.6,
       13.6, 13.4, 13.4, 12.6, 13. , 12.4, 11.8])

In [23]:
sepal_length>5

array([ True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True, False, False, False,
        True,  True, False, False,  True,  True,  True, False, False,
        True, False, False,  True, False, False, False, False,  True,
       False,  True, False,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [25]:
sepal_length.shape

(150,)

In [26]:
reshaped_array = sepal_length.reshape(50, 3)
reshaped_array

array([[5.1, 4.9, 4.7],
       [4.6, 5. , 5.4],
       [4.6, 5. , 4.4],
       [4.9, 5.4, 4.8],
       [4.8, 4.3, 5.8],
       [5.7, 5.4, 5.1],
       [5.7, 5.1, 5.4],
       [5.1, 4.6, 5.1],
       [4.8, 5. , 5. ],
       [5.2, 5.2, 4.7],
       [4.8, 5.4, 5.2],
       [5.5, 4.9, 5. ],
       [5.5, 4.9, 4.4],
       [5.1, 5. , 4.5],
       [4.4, 5. , 5.1],
       [4.8, 5.1, 4.6],
       [5.3, 5. , 7. ],
       [6.4, 6.9, 5.5],
       [6.5, 5.7, 6.3],
       [4.9, 6.6, 5.2],
       [5. , 5.9, 6. ],
       [6.1, 5.6, 6.7],
       [5.6, 5.8, 6.2],
       [5.6, 5.9, 6.1],
       [6.3, 6.1, 6.4],
       [6.6, 6.8, 6.7],
       [6. , 5.7, 5.5],
       [5.5, 5.8, 6. ],
       [5.4, 6. , 6.7],
       [6.3, 5.6, 5.5],
       [5.5, 6.1, 5.8],
       [5. , 5.6, 5.7],
       [5.7, 6.2, 5.1],
       [5.7, 6.3, 5.8],
       [7.1, 6.3, 6.5],
       [7.6, 4.9, 7.3],
       [6.7, 7.2, 6.5],
       [6.4, 6.8, 5.7],
       [5.8, 6.4, 6.5],
       [7.7, 7.7, 6. ],
       [6.9, 5.6, 7.7],
       [6.3, 6.7

Save / Load NumPy arrays

In [27]:
np.save("iris.numpy.npy",reshaped_array)

In [28]:
loaded_array=np.load("iris.numpy.npy")
loaded_array

array([[5.1, 4.9, 4.7],
       [4.6, 5. , 5.4],
       [4.6, 5. , 4.4],
       [4.9, 5.4, 4.8],
       [4.8, 4.3, 5.8],
       [5.7, 5.4, 5.1],
       [5.7, 5.1, 5.4],
       [5.1, 4.6, 5.1],
       [4.8, 5. , 5. ],
       [5.2, 5.2, 4.7],
       [4.8, 5.4, 5.2],
       [5.5, 4.9, 5. ],
       [5.5, 4.9, 4.4],
       [5.1, 5. , 4.5],
       [4.4, 5. , 5.1],
       [4.8, 5.1, 4.6],
       [5.3, 5. , 7. ],
       [6.4, 6.9, 5.5],
       [6.5, 5.7, 6.3],
       [4.9, 6.6, 5.2],
       [5. , 5.9, 6. ],
       [6.1, 5.6, 6.7],
       [5.6, 5.8, 6.2],
       [5.6, 5.9, 6.1],
       [6.3, 6.1, 6.4],
       [6.6, 6.8, 6.7],
       [6. , 5.7, 5.5],
       [5.5, 5.8, 6. ],
       [5.4, 6. , 6.7],
       [6.3, 5.6, 5.5],
       [5.5, 6.1, 5.8],
       [5. , 5.6, 5.7],
       [5.7, 6.2, 5.1],
       [5.7, 6.3, 5.8],
       [7.1, 6.3, 6.5],
       [7.6, 4.9, 7.3],
       [6.7, 7.2, 6.5],
       [6.4, 6.8, 5.7],
       [5.8, 6.4, 6.5],
       [7.7, 7.7, 6. ],
       [6.9, 5.6, 7.7],
       [6.3, 6.7

In [29]:
loaded_array.shape

(50, 3)

Compare NumPy performance with Python lists

In [30]:
import time

In [31]:
# python list
python_list = list(sepal_length)
start = time.time()
[x+1 for x in python_list]
end = time.time()
print("python list item :",end-start)

python list item : 0.006400585174560547


In [32]:
start = time.time()
sepal_length + 1
end = time.time()
print("NumPy time:", end - start)

NumPy time: 0.0
